services:
  postgres:
    image: 'postgres:18.0'
    container_name: full-stack-postgres
    environment:
      - 'POSTGRES_DB=fullstackdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - "5432:5432"
