/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Todo {
  id?: number;
  title?: string;
  createdBy?: string;
  createdAt?: string;
  completedBy?: string;
  completedAt?: string;
}
