/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserInfo {
  username?: string;
  email?: string;
  fullName?: string;
  roles?: string[];
}
