spring.application.name: full-stack-app
---
spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/fullstackdb
  username: admin
  password: secret
---
spring.security.oauth2.client:
  registration:
    keycloak:
      client-id: full-stack-app
      client-secret: secret
      authorization-grant-type: authorization_code
      redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
      scope: openid, profile, email
  provider:
    keycloak:
      issuer-uri: http://localhost:9000/realms/full-stack